/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "SlackClientID": {
      "type": "sst.sst.Secret"
      "value": any
    }
  }
}
