#!/bin/sh

echo $SST_RESOURCE_Database

USERNAME=$(echo $SST_RESOURCE_Database | jq -r '.username')
PASSWORD=$(echo $SST_RESOURCE_Database | jq -r '.password')

mysql -h "aws.connect.psdb.cloud" -u $USERNAME -p$PASSWORD sst
